export const BRUNO_TABLE_COMMIT_PROBE_DIAGNOSTIC_SENTINEL =
  "BRUNO_TABLE_COMMIT_PROBE_DIAGNOSTIC_V1";

export const BRUNO_TABLE_GESTURE_TIMING_DIAGNOSTIC_SENTINEL =
  "BRUNO_TABLE_GESTURE_TIMING_DIAGNOSTIC_V1";

export const BRUNO_TABLE_TEST_LISTENER_DIAGNOSTIC_SENTINEL =
  "BRUNO_TABLE_TEST_LISTENER_DIAGNOSTIC_V1";
