packages:
  - "packages/*"

autoInstallPeers: false

allowBuilds:
  msgpackr-extract: false

catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.8
  vite-plus: 0.2.8
minimumReleaseAgeExclude:
  - effect-view-server@4.2.4 || 4.2.5 || 4.2.6 || 4.2.7 || 4.2.8
  - "@vitejs/plugin-react@6.1.0"
overrides:
  vite: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
